import { LibraryItem, Category, SubCategory } from "./types";

export const PEST_DISEASE_LIBRARY: LibraryItem[] = [
  // --- HAMA PENGHISAP & PENGGEREK (1-25) ---
  { 
    id: "1", 
    name: "Wereng Cokelat (Nilaparvata lugens)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menghisap cairan batang padi, menyebabkan tanaman menguning dan mengering seperti terbakar (hopperburn).", 
    plants: ["Padi"],
    lifecycle: "Telur (7-10 hari), Nimfa (12-15 hari), Dewasa (10-20 hari). Total 25-30 hari.",
    visualTraits: ["Berwarna cokelat muda/tua", "Titik hitam pada sayap", "Berkumpul di pangkal batang"],
    controlGuide: "Gunakan jamur Beauveria bassiana, musuh alami laba-laba, atau varietas tahan seperti Inpari."
  },
  { 
    id: "2", 
    name: "Kutu Kebul (Bemisia tabaci)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Vektor virus Gemini. Menghisap nutrisi daun dan menghasilkan embun jelaga.", 
    plants: ["Cabai", "Tomat", "Terong", "Kedelai"],
    lifecycle: "Telur di bawah daun, nimfa menetap. Siklus 2-4 minggu.",
    visualTraits: ["Serangga putih kecil bertepung", "Terbang seperti awan putih jika digoyang"],
    controlGuide: "Pasang perangkap kuning, gunakan mulsa perak, atau semprot insektisida nabati minyak mimba."
  },
  { 
    id: "3", 
    name: "Penggerek Batang Padi Kuning (Scirpophaga incertulas)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Larva memakan jaringan dalam batang padi menyebabkan 'sundep' (vegetatif) atau 'beluk' (generatif).", 
    plants: ["Padi"],
    lifecycle: "Ngengat bertelur di ujung daun. Larva masuk batang. Siklus 40-60 hari.",
    visualTraits: ["Ngengat kuning muda dengan titik hitam", "Batang padi mudah dicabut"],
    controlGuide: "Tanam serempak, kumpulkan kelompok telur, atau gunakan feromon trap."
  },
  { 
    id: "4", 
    name: "Kutu Daun (Aphis gossypii)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menghisap cairan daun muda sehingga mengerut dan kerdil.", 
    plants: ["Cabai", "Semangka", "Jeruk", "Kapas"],
    lifecycle: "Berkembang biak sangat cepat secara partenogenesis di cuaca panas.",
    visualTraits: ["Tubuh lunak hijau/hitam", "Kornikel di bagian belakang", "Sering dikerubuti semut"],
    controlGuide: "Gunakan predator predator ladybug atau larutan sabun kalium."
  },
  { 
    id: "5", 
    name: "Walang Sangit (Leptocorisa oratorius)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menghisap bulir padi fase masak susu menyebabkan bulir hampa atau bercak.", 
    plants: ["Padi", "Rumput-rumputan"],
    lifecycle: "Telur cokelat di atas daun. Nimfa hijau. Dewasa cokelat ramping.",
    visualTraits: ["Bau menyengat", "Tubuh ramping antena panjang"],
    controlGuide: "Gunakan umpan bangkai ikan/kepiting untuk menarik dan membunuh serangga dewasa."
  },
  { 
    id: "6", 
    name: "Thrips (Thrips parvispinus)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menyebabkan keriting daun dan bercak keperakan pada bagian bawah daun.", 
    plants: ["Cabai", "Bawang Merah", "Tomat"],
    lifecycle: "Telur dalam jaringan daun. Nimfa aktif. Siklus singkat 7-12 hari.",
    visualTraits: ["Sangat kecil kuning/hitam", "Daun melengkung ke atas"],
    controlGuide: "Gunakan perangkap warna biru dan semprotkan ekstasi tembakau."
  },
  { 
    id: "7", 
    name: "Penggerek Polong Kedelai (Etiella zinckenella)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Larva masuk ke dalam polong dan memakan biji kedelai.", 
    plants: ["Kedelai", "Kacang Hijau", "Kacang Tanah"],
    lifecycle: "Telur di kelopak bunga. Larva merusak polong. Pupa di tanah.",
    visualTraits: ["Adanya lubang pada polong", "Biji rusak di dalam"],
    controlGuide: "Olah tanah dengan baik, tanam serempak, dan gunakan varietas tahan."
  },
  { 
    id: "8", 
    name: "Kepinding Tanah (Scotinophara coarctata)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menghisap cairan di pangkal batang padi, menyebabkan tanaman layu.", 
    plants: ["Padi"],
    lifecycle: "Dewasa aktif di malam hari. Telur berkelompok di pangkal batang.",
    visualTraits: ["Warna hitam kusam", "Bentuk oval keras", "Berkumpul di bawah permukaan air"],
    controlGuide: "Penggenangan sawah sesaat atau gunakan jamur Metarhizium anisopliae."
  },
  { 
    id: "9", 
    name: "Lalat Buah (Bactrocera spp.)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menusukkan telur ke dalam buah. Larva memakan daging buah hingga busuk.", 
    plants: ["Mangga", "Cabai", "Jambu", "Jeruk"],
    lifecycle: "Dewasa bertelur di buah. Larva (belatung) merusak. Pupa di tanah.",
    visualTraits: ["Buah busuk prematur", "Ada bekas tusukan hitam pada kulit"],
    controlGuide: "Gunakan perangkap metil eugenol (Petrogenol) dan pembungkusan buah."
  },
  { 
    id: "10", 
    name: "Kutu Dompolan (Planococcus citri)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menghisap cairan tanaman dan mengeluarkan madu yang memicu jamur jelaga.", 
    plants: ["Kopi", "Kakao", "Jeruk"],
    lifecycle: "Sangat lambat bergerak. Sering terlindung di sela-sela buah/batang.",
    visualTraits: ["Putih seperti kapas", "Berkelompok rapat pada buah/cabang"],
    controlGuide: "Pangkas cabang yang terlalu rimbun dan gunakan musuh alami Cryptolaemus."
  },
  { 
    id: "11", 
    name: "Penggerek Batang Jagung (Ostrinia furnacalis)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Larva menggerek batang jagung, mengganggu transportasi nutrisi.", 
    plants: ["Jagung", "Sorgum"],
    lifecycle: "Telur di bawah daun. Larva menggerek tongkol dan batang.",
    visualTraits: ["Lubang pada batang", "Adanya kotoran cokelat (frass) di luar lubang"],
    controlGuide: "Tumpang sari dengan kacang tanah atau gunakan Bacillus thuringiensis."
  },
  { 
    id: "12", 
    name: "Wereng Hijau (Nephotettix virescens)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Vektor utama virus Tungro yang sangat mematikan bagi padi.", 
    plants: ["Padi"],
    lifecycle: "Telur dalam pelepah daun. Nimfa dan dewasa menghisap cairan daun.",
    visualTraits: ["Berwarna hijau terang", "Ekor meruncing", "Lari menyamping jika didekati"],
    controlGuide: "Eradikasi tanaman sakit dan kendalikan populasi wereng sejak persemaian."
  },
  { 
    id: "13", 
    name: "Kutu Loncat Lamtoro (Heteropsylla cubana)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menghisap pucuk daun muda sehingga tanaman menjadi gundul.", 
    plants: ["Lamtoro"],
    lifecycle: "Sangat eksplosif di musim kemarau.",
    visualTraits: ["Serangga kecil cokelat/hijau", "Melompat jika disentuh"],
    controlGuide: "Gunakan predator Curinus coeruleus atau varietas lamtoro tahan."
  },
  { 
    id: "14", 
    name: "Hama Ganjur (Orseolia oryzae)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Larva merusak titik tumbuh padi sehingga daun menjadi seperti bawang.", 
    plants: ["Padi"],
    lifecycle: "Lalat kecil bertelur di pelepah daun. Larva masuk ke titik tumbuh.",
    visualTraits: ["Daun menggulung seperti pipa/bawang", "Puncak tanaman mati"],
    controlGuide: "Gunakan lampu perangkap (light trap) dan hindari penggunaan urea berlebih."
  },
  { 
    id: "15", 
    name: "Kutu Perisai (Lepidosaphes beckii)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menempel pada kulit buah dan batang jeruk untuk menghisap cairan.", 
    plants: ["Jeruk", "Kopi"],
    lifecycle: "Betina menetap di bawah cangkang keras pelindung.",
    visualTraits: ["Cangkang cokelat seperti kerang", "Daun menguning dan gugur"],
    controlGuide: "Gunakan semprotan minyak (white oil) untuk menutup pori pernapasan kutu."
  },
  { 
    id: "16", 
    name: "Penggerek Buah Kakao (Conopomorpha cramerella)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Larva merusak plasenta dan biji kakao, buah menjadi sulit dibuka.", 
    plants: ["Kakao", "Rambutan"],
    lifecycle: "Telur di kulit buah. Larva langsung masuk ke dalam. Pupa di permukaan daun kering.",
    visualTraits: ["Buah matang belang", "Biji lengket dan kecil-kecil"],
    controlGuide: "Kondomisasi (pembungkusan buah) dan panen sering (PSPSP)."
  },
  { 
    id: "17", 
    name: "Lalat Bibit (Atherigona exigua)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menyerang tanaman jagung yang baru tumbuh, mematikan titik tumbuh.", 
    plants: ["Jagung", "Padi"],
    lifecycle: "Lalat kecil bertelur di daun muda. Larva menggerek ke arah pangkal.",
    visualTraits: ["Pucuk layu dan mengering", "Larva putih di dalam pangkal batang"],
    controlGuide: "Tanam serempak dan gunakan perlakuan benih (seed treatment) sistemik."
  },
  { 
    id: "18", 
    name: "Penggerek Batang Tebu (Chilo sacchariphagus)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menguras kadar gula dan merusak struktur batang tebu.", 
    plants: ["Tebu"],
    lifecycle: "Siklus hidup 2 bulan. Larva aktif berpindah antar ruas batang.",
    visualTraits: ["Ruas batang berlubang", "Tanaman mudah patah ditiup angin"],
    controlGuide: "Pelepasan parasitoid telur Trichogramma spp."
  },
  { 
    id: "19", 
    name: "Aphid Persik (Myzus persicae)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Vektor virus yang menyerang berbagai tanaman hortikultura.", 
    plants: ["Kentang", "Cabai", "Tembakau"],
    lifecycle: "Berkembang biak cepat di suhu sejuk pegunungan.",
    visualTraits: ["Tubuh hijau muda transparan", "Sangat pasif menempel di balik daun"],
    controlGuide: "Gunakan mulsa plastik perak untuk memantulkan cahaya matahari."
  },
  { 
    id: "20", 
    name: "Ulat Grayak Frugiperda (Spodoptera frugiperda)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Hama invasif yang menyerang titik tumbuh jagung dengan sangat rakus.", 
    plants: ["Jagung", "Sorgum", "Tebu"],
    lifecycle: "Siklus 30 hari. Sangat destruktif pada fase larva instar 3-6.",
    visualTraits: ["Kepala ada tanda Y terbalik", "4 titik di segmen terakhir membentuk kotak"],
    controlGuide: "Semprot agens hayati bakteri Bt atau kumpulkan larva secara manual."
  },
  { 
    id: "21", 
    name: "Kumbang Janjang Sawit (Elaeidobius kamerunicus)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Meskipun penyerbuk, populasinya harus dikelola agar tidak merusak bunga jantan berlebih.", 
    plants: ["Kelapa Sawit"],
    lifecycle: "Berkembang biak di bunga jantan yang sudah mekar.",
    visualTraits: ["Kumbang moncong kecil cokelat", "Aroma bunga jantan sangat kuat"],
    controlGuide: "Manajemen populasi yang seimbang antara bunga jantan dan betina."
  },
  { 
    id: "22", 
    name: "Siput Telanjang (Parmarion pupillaris)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Bukan serangga, tapi penghisap/pemakan jaringan sayuran di malam hari.", 
    plants: ["Sayuran Daun", "Anggrek"],
    lifecycle: "Hemafrodit, bertelur di tempat lembap/onggokan sampah.",
    visualTraits: ["Tubuh lunak berlendir", "Tanpa cangkang", "Jejak lendir mengkilap"],
    controlGuide: "Taburkan abu dapur atau garam di sekitar bedengan tanaman."
  },
  { 
    id: "23", 
    name: "Lalat Penggorok Daun (Liriomyza huidobrensis)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Larva membuat saluran berliku di dalam epidermis daun.", 
    plants: ["Bawang Merah", "Kentang", "Krisan"],
    lifecycle: "Larva berada di dalam jaringan daun. Pupa di permukaan tanah.",
    visualTraits: ["Garis putih berkelok-kelok pada daun", "Warna daun kusam"],
    controlGuide: "Pasang perangkap kuning dan gunakan kain pelapis bedengan."
  },
  { 
    id: "24", 
    name: "Kutu Sisik Hijau (Coccus viridis)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menempel statis pada tulang daun kopi untuk menghisap nutrisi.", 
    plants: ["Kopi", "Teh", "Jeruk"],
    lifecycle: "Tubuh lunak, dilindungi lapisan lilin tipis.",
    visualTraits: ["Lonjong pipih hijau terang", "Sering di sepanjang tulang daun utama"],
    controlGuide: "Gendalikan semut yang melindungi kutu ini dari predator."
  },
  { 
    id: "25", 
    name: "Ulat Bor Buah (Helicoverpa armigera)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Memasukkan setengah badannya ke dalam buah untuk makan.", 
    plants: ["Tomat", "Jagung", "Cabai", "Kapas"],
    lifecycle: "Sangat polifag (padi, sayur, buah). Pupa di dalam tanah.",
    visualTraits: ["Warna ulat bervariasi hijau/cokelat", "Lubang besar pada buah"],
    controlGuide: "Gunakan perangkap feromon atau tumpang sari dengan jagung sebagai trap crop."
  },

  // --- HAMA PEMAKAN DAUN & AKAR (25-40) ---
  { 
    id: "26", 
    name: "Ulat Grayak (Spodoptera litura)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Memakan daun secara berkelompok hingga menyisakan tulang daun saja.", 
    plants: ["Hampir semua jenis sayuran", "Kedelai"],
    lifecycle: "Telur ditutup bulu halus. Larva aktif di malam hari.",
    visualTraits: ["Bercak hitam berbentuk bulan sabit di bagian samping", "Tubuh gemuk hijau tua"],
    controlGuide: "Kumpulkan telur di pagi hari dan gunakan ekstrak sirsak/gadung."
  },
  { 
    id: "27", 
    name: "Ulat Krop Kubis (Crocidolomia pavonana)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Memakan titik tumbuh kubis sehingga tidak terbentuk krop/bulatan.", 
    plants: ["Kubis", "Sawi", "Brokoli"],
    lifecycle: "Larva menyerang bagian dalam krop yang terlindung.",
    visualTraits: ["Garis putih di punggung", "Sangat rakus merusak tunas tengah"],
    controlGuide: "Tanam sawi jabung sebagai tanaman pemerangkap di pinggir lahan."
  },
  { 
    id: "28", 
    name: "Ulat Daun Pisang (Erionota thrax)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Menggulung daun pisang untuk tempat tinggal dan makan.", 
    plants: ["Pisang"],
    lifecycle: "Telur di bawah daun. Larva membuat gulungan besar.",
    visualTraits: ["Gulungan daun silinder pada pisang", "Larva tertutup lapisan lilin putih"],
    controlGuide: "Kumpulkan dan musnahkan gulungan daun secara manual."
  },
  { 
    id: "29", 
    name: "Belalang Kayu (Valanga nigricornis)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Memakan pinggiran daun dalam jumlah besar saat populasi meledak.", 
    plants: ["Jagung", "Kelapa", "Tanaman Hutan"],
    lifecycle: "Telur di dalam tanah. Nimfa berwarna hijau, dewasa cokelat.",
    visualTraits: ["Tubuh besar cokelat keabuan", "Kaki belakang sangat kuat"],
    controlGuide: "Lestarikan burung pemakan serangga dan olah tanah secara intensif untuk merusak sarang telur."
  },
  { 
    id: "30", 
    name: "Kumbang Tanduk (Oryctes rhinoceros)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Merusak titik tumbuh kelapa sawit/kelapa, menyebabkan daun seperti huruf V.", 
    plants: ["Kelapa Sawit", "Kelapa"],
    lifecycle: "Larva berkembang biak di tumpukan sampah atau batang lapuk.",
    visualTraits: ["Kumbang besar hitam mengkilap", "Tanduk kecil di kepala", "Lubang lubang pada pelepah"],
    controlGuide: "Hancurkan media perkembangbiakan (batang lapuk) dan gunakan perangkap feromon."
  },
  { 
    id: "31", 
    name: "Uret/Engker (Lepidiota stigma)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Larva pemakan akar yang menyebabkan tanaman layu dan mati mendadak.", 
    plants: ["Tebu", "Singkong", "Bibit Sengon"],
    lifecycle: "Dewasa berupa kumbang cokelat. Larva hidup di dalam tanah selama 1 tahun.",
    visualTraits: ["Larva putih bentuk C besar", "Kepala cokelat keras"],
    controlGuide: "Olah tanah dalam dan gunakan agens hayati jamur Metarhizium."
  },
  { 
    id: "32", 
    name: "Ulat Tanah (Agrotis ipsilon)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Memotong batang tanaman muda di permukaan tanah pada malam hari.", 
    plants: ["Sayuran Muda", "Tembakau", "Jagung"],
    lifecycle: "Larva bersembunyi di tanah saat siang. Ngengat aktif malam.",
    visualTraits: ["Ulat hitam/abu-abu melingkar jika disentuh", "Batang tanaman terpotong rapi"],
    controlGuide: "Gunakan umpan dedak/sekam campur insektisida nabati diletakkan di tanah."
  },
  { 
    id: "33", 
    name: "Ganjur Bawang (Heliothis spp.)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Larva masuk ke dalam pipa daun bawang merah dan makan dari dalam.", 
    plants: ["Bawang Merah", "Bawang Putih"],
    lifecycle: "Ngengat bertelur di ujung daun. Larva langsung masuk ke pipa daun.",
    visualTraits: ["Ulat di bagian dalam rongga daun", "Ujung daun mengering"],
    controlGuide: "Pemantauan kelompok telur dan penggunaan lampu perangkap biru."
  },
  { 
    id: "34", 
    name: "Ulat Jengkal (Chrysodeixis chalcites)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Memakan daun hingga hanya tersisa pembuluh darah daun/tulang daun.", 
    plants: ["Kedelai", "Tomat", "Kacang-kacangan"],
    lifecycle: "Berjalan dengan cara melengkungkan badan seperti mengukur jengkal.",
    visualTraits: ["Warna hijau terang dengan garis lateral", "Kepala lebih kecil"],
    controlGuide: "Semprotkan ekstrak daun sirsak atau gunakan musuh alami tawon parasit."
  },
  { 
    id: "35", 
    name: "Kumbang Bubuk Beras (Sitophilus oryzae)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Hama gudang utama yang melubangi butiran beras dan jagung.", 
    plants: ["Beras", "Jagung", "Gandum"],
    lifecycle: "Telur diletakkan di dalam butiran. Larva makan di dalam biji.",
    visualTraits: ["Moncong panjang", "Lubang halus pada butiran beras"],
    controlGuide: "Simpan dengan kelembapan rendah (<12%) dan gunakan daun salam kering di tempat simpan."
  },
  { 
    id: "36", 
    name: "Ulat Tanduk Tomat (Manduca quinquemaculata)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Ulat raksasa yang mampu menghabiskan daun satu tanaman dalam semalam.", 
    plants: ["Tomat", "Tembakau"],
    lifecycle: "Ngengat sangat besar (Sphinx moth). Larva tumbuh sangat cepat.",
    visualTraits: ["Warna hijau sangat cerah", "Tanduk biru/hitam di ekor", "Garis V putih di samping"],
    controlGuide: "Pengambilan manual karena ukurannya yang besar sangat membantu."
  },
  { 
    id: "37", 
    name: "Hama Putih Palsu (Cnaphalocrocis medinalis)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Larva melipat daun padi dan makan bagian dalam, menyisakan kerangka putih.", 
    plants: ["Padi"],
    lifecycle: "Ngengat kecil cokelat terang. Larva melipat daun secara lateral.",
    visualTraits: ["Garis-garis putih pada daun padi", "Daun terlipat/menggulung"],
    controlGuide: "Gunakan pupuk K yang cukup dan jangan terlalu rapat menanam padi."
  },
  { 
    id: "38", 
    name: "Kumbang Daun (Epilachna spp.)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Memakan epidermis daun sayuran, memberikan pola makan berjaring.", 
    plants: ["Kentang", "Tomat", "Terong"],
    lifecycle: "Kumbang berwarna merah/oranye dengan titik-titik hitam.",
    visualTraits: ["Mirip kepik/ladybug tapi memakan tanaman", "Larva berduri kuning"],
    controlGuide: "Lakukan pergiliran tanaman non-Solanaceae (bukan keluarga tomat)."
  },
  { 
    id: "39", 
    name: "Kutu Akar (Rhizoecus spp.)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Hidup di tanah dan menghisap cairan akar, tanaman kerdil tanpa sebab jelas di atas.", 
    plants: ["Kopi", "Teh", "Tanaman Hias"],
    lifecycle: "Betina menetap di akar, sering membawa lapisan lilin putih.",
    visualTraits: ["Lapisan putih di permukaan akar", "Tanaman tetap kerdil meski dipupuk"],
    controlGuide: "Sterilisasi media tanam dan aplikasi nematisida organik."
  },
  { 
    id: "40", 
    name: "Lalat Daun Bibit (Atherigona oryzae)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PEMAKAN_DAUN_AKAR, 
    description: "Menyerang bibit padi sawah/gogo muda di awal tanam.", 
    plants: ["Padi", "Jagung"],
    lifecycle: "Telur di bawah daun bibit. Larva memotong titik tumbuh utama.",
    visualTraits: ["Pucuk layu warna abu-abu", "Tanaman kerdil dan anakan sedikit"],
    controlGuide: "Tanam serempak dan gunakan sistem pengairan yang baik."
  },

  // --- NON-SERANGGA & LAINNYA (41-50) ---
  { 
    id: "41", 
    name: "Tikus Sawah (Rattus argentiventer)", 
    category: Category.HAMA, 
    subCategory: SubCategory.NON_SERANGGA, 
    description: "Merusak rumpun padi secara acak sejak fase semai hingga panen.", 
    plants: ["Padi", "Jagung", "Palawija"],
    lifecycle: "Berkembang biak sangat pesat, indukan bisa melahirkan 10 ekor per bulan.",
    visualTraits: ["Potongan batang miring 45 derajat", "Lubang sarang di pematang", "Jejak jalan tikus"],
    controlGuide: "Gunakan LTBS (Linear Trap Barrier System) dan dorong populasi burung hantu."
  },
  { 
    id: "42", 
    name: "Tungau Merah (Tetranychus urticae)", 
    category: Category.HAMA, 
    subCategory: SubCategory.NON_SERANGGA, 
    description: "Menghisap cairan daun bawah, menyebabkan bintik kuning/putih halus.", 
    plants: ["Cabai", "Bunga Mawar", "Singkong", "Kakao"],
    lifecycle: "Sangat cepat di cuaca panas kering. Kurang dari 1 minggu untuk 1 siklus.",
    visualTraits: ["Bercak halus seperti debu", "Ada jaring halus di balik daun", "Titik merah kecil bergerak"],
    controlGuide: "Tingkatkan kelembapan lahan dan semprot dengan akarisida sulfur."
  },
  { 
    id: "43", 
    name: "Nematoda Bengkak Akar (Meloidogyne spp.)", 
    category: Category.HAMA, 
    subCategory: SubCategory.NON_SERANGGA, 
    description: "Cacing mikro yang masuk ke akar dan menyebabkan pembengkakan (root-knot).", 
    plants: ["Tomat", "Sayuran", "Kopi", "Bibit Sawit"],
    lifecycle: "Hidup dan bertelur di dalam jaringan akar.",
    visualTraits: ["Bintil-bintil besar pada akar", "Tanaman kerdil dan layu mendadak"],
    controlGuide: "Tanam Tagetes (tahi ayam) sebagai penolak nematoda alami."
  },
  { 
    id: "44", 
    name: "Siput Murbei (Pomacea canaliculata)", 
    category: Category.HAMA, 
    subCategory: SubCategory.NON_SERANGGA, 
    description: "Memakan batang padi muda (0-15 HST) di permukaan air.", 
    plants: ["Padi"],
    lifecycle: "Telur berwarna merah muda di pematang atau batang padi.",
    visualTraits: ["Cangkang bulat kuning/emas", "Telur merah mencolok"],
    controlGuide: "Ambil secara manual, pasang saringan di pintu air, atau pelihara bebek."
  },
  { 
    id: "45", 
    name: "Kelelawar Buah (Pteropus spp.)", 
    category: Category.HAMA, 
    subCategory: SubCategory.NON_SERANGGA, 
    description: "Memakan buah-buahan matang di pohon pada malam hari.", 
    plants: ["Mangga", "Rambutan", "Durian"],
    lifecycle: "Aktif malam hari, mencari makan secara berkelompok.",
    visualTraits: ["Buah berlubang besar tidak beraturan", "Kotoran di bawah pohon"],
    controlGuide: "Pembungkusan buah dan pemasangan jala di atas tajuk pohon."
  },
  { 
    id: "46", 
    name: "Tupai Kelapa (Callosciurus notatus)", 
    category: Category.HAMA, 
    subCategory: SubCategory.NON_SERANGGA, 
    description: "Melubangi buah kelapa muda untuk diminum airnya dan dimakan dagingnya.", 
    plants: ["Kelapa", "Kakao"],
    lifecycle: "Aktif di siang hari (diurnal). Bersembunyi di pelepah.",
    visualTraits: ["Lubang rapi pada kelapa/buah kakao", "Tanda bekas gigitan pengerat"],
    controlGuide: "Cegah pergerakannya dengan memasang cincin seng di batang kelapa."
  },
  { 
    id: "47", 
    name: "Babi Hutan (Sus scrofa)", 
    category: Category.HAMA, 
    subCategory: SubCategory.NON_SERANGGA, 
    description: "Membongkar lahan dan memakan tanaman umbi atau anakan sawit.", 
    plants: ["Singkong", "Ubi Jalar", "Kelapa Sawit Muda"],
    lifecycle: "Aktif malam hari, merusak lahan dalam area luas.",
    visualTraits: ["Tanaman tercabut/terbongkar", "Jejak kaki babi", "Kubangan lumpur"],
    controlGuide: "Pemagaran lahan yang kuat atau pemasangan bunyi-bunyian."
  },
  { 
    id: "48", 
    name: "Kutu Sisik Salju (Unaspis citri)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menutupi kulit batang jeruk, menghisap cairan hingga batang pecah/mati.", 
    plants: ["Jeruk"],
    lifecycle: "Betina menetap, jantan sangat kecil bisa terbang.",
    visualTraits: ["Bercak putih seperti salju/bedak pada batang utama", "Kulit batang pecah-pecah"],
    controlGuide: "Sikat batang dengan sikat kawat lunak dan semprot dengan bubur kalium sulfur."
  },
  { 
    id: "49", 
    name: "Wereng Punggung Putih (Sogatella furcifera)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Menghisap cairan daun padi, menyebabkan daun menjadi kusam dan layu.", 
    plants: ["Padi", "Jagung"],
    lifecycle: "Siklus mirip wereng cokelat tapi lebih suka tanaman muda.",
    visualTraits: ["Garis putih memanjang di punggung (scutellum)", "Gerakan lincah melompat"],
    controlGuide: "Gunakan pupuk berimbang dan atur jarak tanam jangan terlalu rapat."
  },
  { 
    id: "50", 
    name: "Penggerek Umbi Kentang (Phthorimaea operculella)", 
    category: Category.HAMA, 
    subCategory: SubCategory.PENGHISAP_PENGGEREK, 
    description: "Larva menggerek daun dan masuk ke dalam umbi kentang baik di lahan maupun gudang.", 
    plants: ["Kentang", "Tomat"],
    lifecycle: "Betina bertelur di dekat mata umbi. Larva membuat terowongan dalam umbi.",
    visualTraits: ["Terowongan kotor dalam umbi", "Daun mengering bergaris putih"],
    controlGuide: "Hindari retakan tanah saat menanam dan gunakan perangkap feromon di gudang."
  },

  // --- PENYAKIT JAMUR (51-75) ---
  { 
    id: "51", 
    name: "Blas Padi (Pyricularia oryzae)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyerang daun (neck blast) dan leher malai (node blast), menyebabkan patah leher.", 
    plants: ["Padi"],
    lifecycle: "Spora tersebar lewat angin. Berkembang pesat jika kelembapan >90% dan pupuk N tinggi.",
    visualTraits: ["Bercak belah ketupat kelabu di tengah", "Pangkal malai membusuk dan patah"],
    controlGuide: "Gunakan varietas tahan (Inpari), kurangi pupuk Nitrogen, dan atur jarak tanam."
  },
  { 
    id: "52", 
    name: "Hawa Pelepah (Rhizoctonia solani)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan busuk pada pelepah padi yang menyebar ke daun bagian atas.", 
    plants: ["Padi", "Jagung", "Kedelai"],
    lifecycle: "Bertahan dalam tanah sebagai sklerotia (butiran keras) selama bertahun-tahun.",
    visualTraits: ["Bercak abu-abu kehijauan tidak beraturan", "Terdapat bintil-bintil cokelat pada pelepah"],
    controlGuide: "Perbaiki sanitasi lahan dan gunakan jamur antagonis Trichoderma harzianum."
  },
  { 
    id: "53", 
    name: "Antraknosa / Patek (Colletotrichum spp.)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan buah membusuk dengan bercak melingkar, sangat merugikan di musim hujan.", 
    plants: ["Cabai", "Bawang Merah", "Tomat"],
    lifecycle: "Spora aktif menyebar lewat percikan air hujan dan angin kencang.",
    visualTraits: ["Bercak melingkar melekuk ke dalam", "Titik hitam konsentris di tengah bercak"],
    controlGuide: "Musnahkan buah terinfeksi segera, hindari pengairan di atas tajuk daun."
  },
  { 
    id: "54", 
    name: "Bulai Jagung (Peronosclerospora maydis)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Penyakit sistemik yang menghambat pembentukan klorofil daun jagung.", 
    plants: ["Jagung"],
    lifecycle: "Spora diproduksi pada malam hari dengan kelembapan tinggi. Menular lewat angin.",
    visualTraits: ["Garis putih/kuning sejajar tulang daun", "Lapisan tepung putih di bawah daun"],
    controlGuide: "Gunakan benih tahan bulai dan perlakuan benih (seed treatment) metalaksil."
  },
  { 
    id: "55", 
    name: "Layu Fusarium (Fusarium oxysporum)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Penyakit tular tanah yang menyumbat pembuluh kayu tanaman sehingga layu.", 
    plants: ["Tomat", "Cabai", "Pisang", "Bawang Merah"],
    lifecycle: "Spora mikro dan klamidospora bertahan sangat lama di dalam tanah.",
    visualTraits: ["Tulang daun menguning", "Layu saat siang, segar pagi hari", "Batang cokelat jika dibelah"],
    controlGuide: "Gunakan kapur pertanian untuk menjaga pH tanah dan aplikasi Trichoderma."
  },
  { 
    id: "56", 
    name: "Busuk Daun / Early Blight (Alternaria solani)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan bercak cokelat bergelang pada daun tua.", 
    plants: ["Kentang", "Tomat"],
    lifecycle: "Berlindung di sisa tanaman atau biji. Menyukai suhu hangat dan lembap.",
    visualTraits: ["Bercak konsentris mirip 'target' panahan", "Daun menguning dan gugur"],
    controlGuide: "Lakukan rotasi tanaman dengan tanaman bukan keluarga terong-terongan."
  },
  { 
    id: "57", 
    name: "Busuk Hitam Kakao (Phytophthora palmivora)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyerang buah, batang (kanker batang), dan daun kakao.", 
    plants: ["Kakao", "Karet", "Kelapa"],
    lifecycle: "Menular lewat percikan air. Spora berenang (zoospora) sangat aktif di air.",
    visualTraits: ["Buah berubah cokelat kehitaman mulai dari ujung", "Lapisan putih berdebu pada buah"],
    controlGuide: "Pangkas tajuk agar tidak lembap dan kubur buah yang sakit."
  },
  { 
    id: "58", 
    name: "Jamur Akar Putih (Rigidoporus microporus)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Penyakit akar yang menghancurkan perakaran tanaman perkebunan kayu.", 
    plants: ["Karet", "Kelapa Sawit", "Pohon Kayu"],
    lifecycle: "Menular melalui kontak akar sehat dengan tunggul pohon sakit.",
    visualTraits: ["Benang-benang putih (rizomorf) menempel kuat di akar", "Badan buah seperti kipas oranye"],
    controlGuide: "Bongkar tunggul lama dan taburkan belerang di sekitar lubang tanam."
  },
  { 
    id: "59", 
    name: "Embun Tepung (Oidium spp.)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menutupi permukaan daun dengan lapisan putih seperti tepung, menghalangi fotosintesis.", 
    plants: ["Mentimun", "Melon", "Mangga", "Karet"],
    lifecycle: "Spora tersebar lewat angin. Berkembang di musim kemarau yang lembap.",
    visualTraits: ["Serbuk putih pada permukaan atas daun", "Daun mengerut dan kecokelatan"],
    controlGuide: "Semprotkan larutan baking soda encer atau fungisida berbahan aktif sulfur."
  },
  { 
    id: "60", 
    name: "Karat Daun (Hemileia vastatrix)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Penyakit daun paling merusak pada kopi Arabika.", 
    plants: ["Kopi"],
    lifecycle: "Spora berwarna oranye yang menular sangat cepat pada suhu sejuk pegunungan.",
    visualTraits: ["Bercak kuning/oranye seperti karat di bawah daun", "Daun rontok parah"],
    controlGuide: "Pangkas pohon pelindung dan gunakan varietas tahan seperti USDA atau S-Line."
  },
  { 
    id: "61", 
    name: "Akar Gada (Plasmodiophora brassicae)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan akar membengkak besar mirip gada, menghambat serapan air.", 
    plants: ["Kubis", "Sawi", "Brokoli"],
    lifecycle: "Spora istirahat bertahan di tanah asam hingga 10 tahun.",
    visualTraits: ["Akar bengkak tidak beraturan", "Tanaman layu padahal tanah basah"],
    controlGuide: "Naikkan pH tanah di atas 7.0 dengan kapur dolomit tinggi."
  },
  { 
    id: "62", 
    name: "Bercak Daun Cercospora", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan bintik mata burung pada daun sayuran.", 
    plants: ["Cabai", "Kacang Tanah", "Jagung"],
    lifecycle: "Spora bertahan pada sisa tanaman di permukaan tanah.",
    visualTraits: ["Bercak bulat kecil kelabu dengan pinggiran cokelat/merah"],
    controlGuide: "Kurangi kelembapan dan semprot dengan ekstrak jahe/kunyit."
  },
  { 
    id: "63", 
    name: "Busuk Buah Botrytis (Botrytis cinerea)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menutupi buah dengan jamur abu-abu tebal setelah panen atau saat tinggi kelembapan.", 
    plants: ["Stroberi", "Anggur", "Tomat"],
    lifecycle: "Menginfeksi melalui luka atau kelopak bunga yang layu.",
    visualTraits: ["Lapisan abu-abu berbulu pada buah", "Buah menjadi sangat lunak"],
    controlGuide: "Gunakan kemasan yang berlubang sirkulasi dan simpan di suhu dingin."
  },
  { 
    id: "64", 
    name: "Penyakit Embun Bulu (Pseudoperonospora cubensis)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan bercak kuning bersudut yang dibatasi tulang daun.", 
    plants: ["Mentimun", "Melon", "Semangka"],
    lifecycle: "Menular lewat air hujan. Sangat destruktif di musim penghujan.",
    visualTraits: ["Bercak bersudut kuning di atas, ungu keabuan di bawah daun"],
    controlGuide: "Gunakan sistem irigasi tetes daripada semprotan atas."
  },
  { 
    id: "65", 
    name: "Busuk Batang Sclerotium", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan busuk pangkal batang dengan miselium putih tebal.", 
    plants: ["Kacang Tanah", "Kedelai", "Cabai"],
    lifecycle: "Menghasilkan butiran cokelat (sklerotia) seperti biji sawi di pangkal batang.",
    visualTraits: ["Jamur putih seperti kapas di pangkal tanaman", "Tanaman mati mendadak"],
    controlGuide: "Gunakan agen hayati Gliocladium dan jangan menanam terlalu dalam."
  },
  { 
    id: "66", 
    name: "Sigatoka Hitam (Mycosphaerella fijiensis)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Penyakit bercak daun yang memperpendek umur produktif pohon pisang.", 
    plants: ["Pisang"],
    lifecycle: "Spora terbawa angin. Merusak jaringan pengangkut di daun.",
    visualTraits: ["Garis cokelat sejajar pada daun yang kemudian melebar hitam"],
    controlGuide: "Pangkas daun yang terinfeksi dan bakar jauh dari lahan."
  },
  { 
    id: "67", 
    name: "Jamur Upas (Corticium salmonicolor)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyerang cabang tanaman keras, menyebabkan kulit kayu mengelupas dan mati.", 
    plants: ["Jeruk", "Karet", "Kakao"],
    lifecycle: "Menyukai lingkungan yang sangat lembap dan gelap (kurang matahari).",
    visualTraits: ["Lapisan kerak merah muda pada cabang/batang", "Cabang mati pucuk"],
    controlGuide: "Kerok jamur dan olesi dengan bubur Bordeaux (kapur + terusi)."
  },
  { 
    id: "68", 
    name: "Penyakit Rebah Kecambah (Pythium spp.)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyerang bibit di persemaian, batang di permukaan tanah busuk dan bibit rebah.", 
    plants: ["Hampir semua bibit sayuran"],
    lifecycle: "Phythol menginfeksi jaringan lunak bibit yang terlalu basah.",
    visualTraits: ["Leher batang bibit mengecil and membusuk", "Bibit rebah serempak"],
    controlGuide: "Jangan gunakan media tanah yang terlalu basah/becek di persemaian."
  },
  { 
    id: "69", 
    name: "Layu Verticillium", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Mirip Fusarium, menyerang berkas pembuluh tanaman.", 
    plants: ["Kentang", "Stroberi", "Tomat"],
    lifecycle: "Tular tanah (soil-borne). Bertahan lama di tanah tanpa inang.",
    visualTraits: ["Daun layu di satu sisi", "Perubahan warna cokelat V di tepi daun"],
    controlGuide: "Gunakan benih bebas penyakit dan rotasi tanaman non-inang."
  },
  { 
    id: "70", 
    name: "Busuk Akar & Pangkal Batang Sawit (Ganoderma)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Penyakit paling mematikan pada kelapa sawit dewasa.", 
    plants: ["Kelapa Sawit", "Kelapa"],
    lifecycle: "Jamur kayu yang memakan jaringan lignin (kayu) dari dalam batang.",
    visualTraits: ["Muncul jamur putih/cokelat keras di pangkal batang (basidiokarp)", "Daun tombak tidak membuka"],
    controlGuide: "Pembongkaran pohon sakit hingga akarnya dan sanitasi lubang tanam."
  },
  { 
    id: "71", 
    name: "Bercak Ungu Bawang (Alternaria porri)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan bercak ungu melekuk pada daun bawang merah.", 
    plants: ["Bawang Merah", "Bawang Putih"],
    lifecycle: "Spora berkembang pesat pada kelembapan tinggi dan embun pagi.",
    visualTraits: ["Bercak ungu dengan pusat keputihan", "Daun patah pada titik bercak"],
    controlGuide: "Gunakan penyiraman air bersih setelah hujan berhenti untuk membilas spora."
  },
  { 
    id: "72", 
    name: "Penyakit Kudis Jeruk (Elsinoe fawcettii)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan benjolan kasar pada kulit buah dan daun jeruk.", 
    plants: ["Jeruk"],
    lifecycle: "Menular lewat percikan air pada jaringan muda yang sedang tumbuh.",
    visualTraits: ["Gabus/benjolan kasar berwarna cokelat terang pada kulit buah"],
    controlGuide: "Lakukan pemangkasan rutin agar sirkulasi udara di dalam tajuk baik."
  },
  { 
    id: "73", 
    name: "Busuk Lunak Buah (Rhizopus stolonifer)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Sering terjadi pasca panen, buah membusuk sangat cepat.", 
    plants: ["Tomat", "Ubi Jalar", "Pepaya"],
    lifecycle: "Jamur hitam yang sering disebut jamur roti. Spora ada di mana-mana.",
    visualTraits: ["Buah berair, lunak, dan muncul bintik hitam berbulu"],
    controlGuide: "Hindari luka pada buah saat panen dan pengemasan."
  },
  { 
    id: "74", 
    name: "Embun Jelaga (Capnodium spp.)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Jamur yang tumbuh di atas madu ekskresi kutu, mengganggu fotosintesis.", 
    plants: ["Mangga", "Kopi", "Jeruk"],
    lifecycle: "Tergantung pada keberadaan hama penghisap (kutu daun/kebul).",
    visualTraits: ["Lapisan hitam seperti jelaga/asap di permukaan daun"],
    controlGuide: "Basmi kutu penghasil madu, maka embun jelaga akan hilang sendiri."
  },
  { 
    id: "75", 
    name: "Penyakit Malformasi Mangga (Fusarium mangiferae)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan bunga dan pucuk mangga tumbuh abnormal menjadi padat.", 
    plants: ["Mangga"],
    lifecycle: "Menular lewat alat pangkas atau serangga vektor.",
    visualTraits: ["Bunga menggumpal seperti brokoli", "Tidak terjadi pembuahan"],
    controlGuide: "Pangkas bagian malformasi 30cm di bawah gejala dan sterilisasi alat."
  },

  // --- PENYAKIT BAKTERI & VIRUS (76-100) ---
  { 
    id: "76", 
    name: "Hawar Daun Bakteri / Kresek (Xanthomonas oryzae)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.BAKTERI, 
    description: "Penyakit bakteri padi yang menyebabkan daun mengering dari pinggir.", 
    plants: ["Padi"],
    lifecycle: "Bakteri masuk lewat pori air daun. Menyebar lewat angin dan air hujan.",
    visualTraits: ["Bercak kuning keabuan bergelombang di tepian daun", "Adanya eksudat kuning pagi hari"],
    controlGuide: "Gunakan pupuk berimbang, hindari pemupukan N berlebihan saat musim hujan."
  },
  { 
    id: "77", 
    name: "Layu Bakteri (Ralstonia solanacearum)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.BAKTERI, 
    description: "Tanaman layu mendadak dan mati dalam waktu singkat (2-3 hari).", 
    plants: ["Tomat", "Cabai", "Kentang", "Pisang"],
    lifecycle: "Bakteri tular tanah yang menyerang jaringan pembuluh angkut.",
    visualTraits: ["Layu cepat tanpa menguning", "Keluar lendir susu jika batang dipotong dan dimasukkan air"],
    controlGuide: "Gunakan rotasi tanaman dan aplikasi bakterisida nabati jahe."
  },
  { 
    id: "78", 
    name: "Busuk Lunak Bakteri (Erwinia carotovora)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.BAKTERI, 
    description: "Menyebabkan busuk basah berbau busuk pada umbi dan sayuran.", 
    plants: ["Kubis", "Wortel", "Kentang", "Bawang"],
    lifecycle: "Menginfeksi lewat luka mekanis atau bekas serangan hama.",
    visualTraits: ["Jaringan menjadi bubur berair", "Bau menyengat yang khas"],
    controlGuide: "Jaga kebersihan alat dan pastikan penyimpanan kering dan beraerasi."
  },
  { 
    id: "79", 
    name: "Penyakit Kudis Bakteri (Xanthomonas campestris)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.BAKTERI, 
    description: "Menyebabkan bercak kerak kasar pada daun dan buah hortikultura.", 
    plants: ["Tomat", "Cabai", "Jeruk (Kanker Jeruk)"],
    lifecycle: "Menular lewat air hujan yang memercikkan bakteri dari permukaan tanah.",
    visualTraits: ["Bercak hitam menonjol kasar pada kulit buah", "Warna kuning di sekitar bercak hitam"],
    controlGuide: "Gunakan benih bersertifikat dan aplikasi tembaga hidroksida."
  },
  { 
    id: "80", 
    name: "Penyakit Darah Pisang (BDB - Blood Disease Bacterium)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.BAKTERI, 
    description: "Penyakit sistemik mematikan pada pisang, buah busuk berwarna kemerahan.", 
    plants: ["Pisang"],
    lifecycle: "Menular lewat alat pertanian yang terkontaminasi atau serangga pengunjung bunga.",
    visualTraits: ["Daging buah busuk cokelat kemerahan", "Jantung pisang layu dan menghitam"],
    controlGuide: "Bungkus jantung pisang sejak muncul dan jangan memindah bibit dari zona merah."
  },
  { 
    id: "81", 
    name: "Virus Kuning / Gemini", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.VIRUS, 
    description: "Penyakit virus paling destruktif pada cabai, ditularkan oleh kutu kebul.", 
    plants: ["Cabai", "Tomat", "Terong"],
    lifecycle: "Virus bereplikasi di dalam tubuh Kutu Kebul (Bemisia tabaci).",
    visualTraits: ["Daun kuning terang merata", "Daun mengerut dan mengecil (keriting)"],
    controlGuide: "Gunakan penghalang fisik (mulsa perak) dan kendalikan vektor kutu kebul."
  },
  { 
    id: "82", 
    name: "Penyakit Tungro Padi", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.VIRUS, 
    description: "Virus kompleks (RTBV & RTSV) yang menyebabkan padi kerdil oranye.", 
    plants: ["Padi"],
    lifecycle: "Ditularkan secara non-persisten oleh Wereng Hijau.",
    visualTraits: ["Tanaman sangat kerdil", "Warna kuning oranye dari ujung daun muda"],
    controlGuide: "Tanam serempak dan eradikasi sumber infeksi (singgang padi)."
  },
  { 
    id: "83", 
    name: "TMV - Tobacco Mosaic Virus", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.VIRUS, 
    description: "Virus mosaik yang menyebabkan penurunan kualitas daun tembakau parah.", 
    plants: ["Tembakau", "Tomat", "Lada"],
    lifecycle: "Sangat stabil, bisa menular lewat sentuhan tangan petani yang merokok.",
    visualTraits: ["Pola mosaik hijau tua dan hijau muda pada daun", "Daun bentuknya abnormal"],
    controlGuide: "Cuci tangan dengan sabun sebelum bekerja di lahan, dilarang merokok di kebun."
  },
  { 
    id: "84", 
    name: "BBTV - Banana Bunchy Top Virus", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.VIRUS, 
    description: "Menyebabkan daun pisang tumbuh menumpuk tegak di atas seperti mahkota.", 
    plants: ["Pisang"],
    lifecycle: "Ditularkan oleh Kutu Daun Pisang (Pentalonia nigronervosa).",
    visualTraits: ["Jarak pelepah sangat pendek", "Daun kurus, kaku, dan mudah patah"],
    controlGuide: "Gunakan bibit hasil kultur jaringan dan basmi kutu daun vektor."
  },
  { 
    id: "85", 
    name: "CPVD - Citrus Vein Phloem Degeneration", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.VIRUS, 
    description: "Penyakit kuning mematikan pada jeruk yang ditularkan kutu psyllid (Diaphorina citri).", 
    plants: ["Jeruk"],
    lifecycle: "Disebabkan oleh bakteri Liberibacter yang hidup di phloem (pembuluh tapis).",
    visualTraits: ["Satu cabang menguning (yellow branch)", "Buah kecil masam, biji hitam"],
    controlGuide: "Gunakan bibit bebas virus (label biru) dan kendalikan kutu psyllid secara rutin."
  },
  { 
    id: "86", 
    name: "Virus Kerdil Hampa Padi (Rice Ragged Stunt Virus)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.VIRUS, 
    description: "Menyebabkan padi kerdil dan malai tidak keluar sempurna/hampa.", 
    plants: ["Padi"],
    lifecycle: "Ditularkan oleh Wereng Cokelat.",
    visualTraits: ["Daun compang-camping/bergerigi", "Tepi daun terpilin"],
    controlGuide: "Manajemen populasi wereng cokelat di awal masa tanam."
  },
  { 
    id: "87", 
    name: "Virus Mosaik Mentimun (CMV)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.VIRUS, 
    description: "Menyebabkan pola mosaik dan buah mengkerut abnormal.", 
    plants: ["Mentimun", "Cabai", "Sawi"],
    lifecycle: "Ditularkan oleh kutu daun (aphid) secara mekanis.",
    visualTraits: ["Buah berbenjol tidak rata", "Motif belang pada daun"],
    controlGuide: "Cabut dan bakar tanaman yang sakit sedini mungkin."
  },
  { 
    id: "88", 
    name: "Virus Tristeza Jeruk (CTV)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.VIRUS, 
    description: "Menyebabkan kematian mendadak atau penurunan vigor jeruk secara drastis.", 
    plants: ["Jeruk"],
    lifecycle: "Ditularkan oleh kutu daun hitam (Toxoptera citricida).",
    visualTraits: ["Gejala pitting (lubang kecil) di jaringan kayu di bawah kulit batang"],
    controlGuide: "Gunakan batang bawah (rootstock) yang toleran seperti Citrumelo."
  },
  { 
    id: "89", 
    name: "Penyakit Sapu Setan (Witches' Broom)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.LAINNYA, 
    description: "Menyebabkan pertumbuhan tunas berlebih dan kerdil pada ubi kayu.", 
    plants: ["Ubi Kayu", "Kacang-kacangan"],
    lifecycle: "Disebabkan oleh Phytoplasma yang ditularkan serangga wereng punggung putih.",
    visualTraits: ["Tunas lateral tumbuh banyak seperti sapu", "Ruas batang memendek"],
    controlGuide: "Jangan gunakan bibit dari tanaman yang sudah menunjukkan gejala."
  },
  { 
    id: "90", 
    name: "Busuk Pangkal Umbi Gajah (Sclerotium rolfsii)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.LAINNYA, 
    description: "Menyerang umbi di dalam tanah, menyebabkan busuk basah putih.", 
    plants: ["Umbi-umbian", "Lili", "Kelor"],
    lifecycle: "Sangat menyukai tanah masam dan kelembapan jenuh.",
    visualTraits: ["Lapisan putih tebal di pangkal batang menular ke umbi"],
    controlGuide: "Aplikasi agens hayati Gliocladium secara rutin."
  },
  { 
    id: "91", 
    name: "Penyakit Alga Merah (Cephaleuros virescens)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.LAINNYA, 
    description: "Alga parasit yang menyebabkan bercak kasar pada daun tanaman perkebunan.", 
    plants: ["Teh", "Kopi", "Jambu"],
    lifecycle: "Berkembang di lingkungan sangat lembap dan gelap (sirkulasi udara buruk).",
    visualTraits: ["Bercak bulat menonjol seperti beludru oranye/merah di daun"],
    controlGuide: "Lakukan pemangkasan tajuk untuk mengurangi kelembapan."
  },
  { 
    id: "92", 
    name: "Busuk Akar Pythium", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan akar tanaman pangan menjadi bubur cokelat.", 
    plants: ["Jagung", "Sorgum"],
    lifecycle: "Spora berenang di air tanah yang menggenang.",
    visualTraits: ["Tanaman kuning dan layu permanen", "Akar hancur jika dicabut"],
    controlGuide: "Perbaiki drainase lahan agar tidak terjadi genangan air."
  },
  { 
    id: "93", 
    name: "Mosaik Kuning Kedelai (SYMV)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.VIRUS, 
    description: "Penyakit mosaik kuning cerah pada daun kedelai.", 
    plants: ["Kedelai"],
    lifecycle: "Ditularkan oleh kutu kebul.",
    visualTraits: ["Pola mosaik kuning yang kontras dengan hijau daun"],
    controlGuide: "Penanaman varietas tahan dan pengendalian vektor kutu."
  },
  { 
    id: "94", 
    name: "Hawar Daun Stemphylium", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan daun bawang merah/putih cepat mengering mulai dari ujung.", 
    plants: ["Bawang Merah", "Bawang Putih"],
    lifecycle: "Spora bertahan di sisa tanaman di permukaan tanah.",
    visualTraits: ["Bercak memanjang cokelat muda yang kemudian menghitam"],
    controlGuide: "Bersihkan sisa tanaman dari lahan setelah panen."
  },
  { 
    id: "95", 
    name: "Penyakit Pasca Panen Busuk Biru (Penicillium spp.)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.LAINNYA, 
    description: "Menyerang buah dalam penyimpanan, menyebabkan busuk berair dengan spora biru.", 
    plants: ["Jeruk", "Apel", "Bawang"],
    lifecycle: "Spora masuk melalui luka kecil saat panen.",
    visualTraits: ["Lapisan spora berwarna biru/hijau pada permukaan buah busuk"],
    controlGuide: "Cuci buah dengan air diklorinasi sebelum disimpan."
  },
  { 
    id: "96", 
    name: "Penyakit Karat Puru (Uromycladium falcatarium)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Penyakit jamur yang menyebabkan benjolan (gall) pada ranting sengon.", 
    plants: ["Sengon"],
    lifecycle: "Spora cokelat tepung sangat mudah tertiup angin.",
    visualTraits: ["Benjolan/puru kasar cokelat pada ranting, daun, dan polong"],
    controlGuide: "Semprot bagian puru dengan cuka atau pangkas cabang yang bergejala."
  },
  { 
    id: "97", 
    name: "Penyakit Busuk Batang Vanili (Fusarium oxysporum f. sp. vanillae)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Penyakit utama yang menghancurkan budidaya vanili.", 
    plants: ["Vanili"],
    lifecycle: "Menular lewat alat pangkas atau air tanah.",
    visualTraits: ["Batang membusuk kecokelatan dan berkerut", "Akar gantung mati"],
    controlGuide: "Gunakan bibit sehat dan jangan melukai batang saat pengikat mulas."
  },
  { 
    id: "98", 
    name: "Penyakit Bule Nilam (Virus)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.VIRUS, 
    description: "Menyebabkan daun nilam menjadi kuning dan kualitas minyak menurun.", 
    plants: ["Nilam"],
    lifecycle: "Menular melalui bibit stek dari pohon induk yang sakit.",
    visualTraits: ["Daun kuning pucat dan ukuran mengecil"],
    controlGuide: "Seleksi bibit stek hanya dari pohon induk yang benar-benar sehat."
  },
  { 
    id: "99", 
    name: "Bercak Daun Phyllosticta", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan bercak cokelat kecil dengan titik hitam di tengah daun jagung.", 
    plants: ["Jagung", "Sorgum"],
    lifecycle: "Bertahan di biji atau sisa tanaman lahan.",
    visualTraits: ["Bercak memanjang tipis kelabu/cokelat"],
    controlGuide: "Olah tanah secara sempurna untuk membenamkan sisa tanaman."
  },
  { 
    id: "100", 
    name: "Busuk Arang (Macrophomina phaseolina)", 
    category: Category.PENYAKIT, 
    subCategory: SubCategory.JAMUR, 
    description: "Menyebabkan busuk pangkal batang yang hitam seperti arang di musim kemarau.", 
    plants: ["Kacang Tanah", "Kedelai", "Sorgum"],
    lifecycle: "Menyerang saat tanaman mengalami stres kekeringan.",
    visualTraits: ["Bagian dalam batang dipenuhi bintik hitam kecil (sklerotia) like charcoal"],
    controlGuide: "Pastikan pengairan cukup di fase pengisian polong/biji."
  },
];
